/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {43, 1, 1};
static const casadi_int casadi_s3[3] = {21, 1, 1};

/* quadrotor_ode_expl_vde_adj:(i0[13],i1[13],i2[8],i3[43])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[3]? arg[3][1] : 0;
  a01=arg[2]? arg[2][0] : 0;
  a01=(a00*a01);
  a02=arg[3]? arg[3][2] : 0;
  a03=arg[2]? arg[2][1] : 0;
  a03=(a02*a03);
  a01=(a01+a03);
  a03=arg[3]? arg[3][3] : 0;
  a04=arg[2]? arg[2][2] : 0;
  a04=(a03*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][4] : 0;
  a05=arg[2]? arg[2][3] : 0;
  a05=(a04*a05);
  a01=(a01+a05);
  a05=arg[3]? arg[3][5] : 0;
  a06=arg[2]? arg[2][4] : 0;
  a06=(a05*a06);
  a01=(a01+a06);
  a06=arg[3]? arg[3][6] : 0;
  a07=arg[2]? arg[2][5] : 0;
  a07=(a06*a07);
  a01=(a01+a07);
  a07=arg[3]? arg[3][7] : 0;
  a08=arg[2]? arg[2][6] : 0;
  a08=(a07*a08);
  a01=(a01+a08);
  a08=arg[3]? arg[3][8] : 0;
  a09=arg[2]? arg[2][7] : 0;
  a09=(a08*a09);
  a01=(a01+a09);
  a09=arg[3]? arg[3][0] : 0;
  a01=(a01/a09);
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a12=arg[0]? arg[0][4] : 0;
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a13=arg[0]? arg[0][5] : 0;
  a14=casadi_sq(a13);
  a11=(a11+a14);
  a14=arg[0]? arg[0][6] : 0;
  a15=casadi_sq(a14);
  a11=(a11+a15);
  a11=sqrt(a11);
  a15=(a10/a11);
  a16=(a01*a15);
  a17=arg[1]? arg[1][9] : 0;
  a18=(a16*a17);
  a19=(a12/a11);
  a20=(a01*a19);
  a21=arg[1]? arg[1][8] : 0;
  a22=(a20*a21);
  a18=(a18-a22);
  a22=(a15*a17);
  a23=(a19*a21);
  a22=(a22-a23);
  a23=(a13/a11);
  a24=arg[1]? arg[1][7] : 0;
  a25=(a23*a24);
  a22=(a22+a25);
  a25=(a01*a22);
  a18=(a18+a25);
  a25=(a01*a23);
  a26=(a25*a24);
  a18=(a18+a26);
  a26=arg[0]? arg[0][12] : 0;
  a27=5.0000000000000000e-01;
  a28=arg[1]? arg[1][6] : 0;
  a28=(a27*a28);
  a29=(a26*a28);
  a18=(a18+a29);
  a29=arg[0]? arg[0][11] : 0;
  a30=arg[1]? arg[1][5] : 0;
  a30=(a27*a30);
  a31=(a29*a30);
  a18=(a18+a31);
  a31=arg[0]? arg[0][10] : 0;
  a32=arg[1]? arg[1][4] : 0;
  a32=(a27*a32);
  a33=(a31*a32);
  a18=(a18+a33);
  a33=(a18/a11);
  a10=(a10+a10);
  a34=(a15/a11);
  a34=(a34*a18);
  a18=(a14/a11);
  a35=(a18/a11);
  a36=(a01*a18);
  a37=(a36*a17);
  a38=(a25*a21);
  a37=(a37+a38);
  a38=(a20*a24);
  a37=(a37+a38);
  a38=(a18*a17);
  a39=(a23*a21);
  a38=(a38+a39);
  a39=(a19*a24);
  a38=(a38+a39);
  a39=(a01*a38);
  a37=(a37+a39);
  a39=(a31*a30);
  a37=(a37+a39);
  a39=(a29*a32);
  a37=(a37-a39);
  a39=arg[1]? arg[1][3] : 0;
  a27=(a27*a39);
  a39=(a26*a27);
  a37=(a37-a39);
  a35=(a35*a37);
  a34=(a34+a35);
  a35=(a23/a11);
  a39=(a36*a21);
  a25=(a25*a17);
  a39=(a39-a25);
  a25=(a16*a24);
  a39=(a39+a25);
  a25=(a18*a21);
  a40=(a23*a17);
  a25=(a25-a40);
  a40=(a15*a24);
  a25=(a25+a40);
  a40=(a01*a25);
  a39=(a39+a40);
  a40=(a31*a28);
  a39=(a39-a40);
  a40=(a26*a32);
  a39=(a39+a40);
  a40=(a29*a27);
  a39=(a39-a40);
  a35=(a35*a39);
  a34=(a34+a35);
  a35=(a19/a11);
  a40=(a18*a24);
  a41=(a19*a17);
  a42=(a15*a21);
  a41=(a41+a42);
  a40=(a40-a41);
  a01=(a01*a40);
  a20=(a20*a17);
  a16=(a16*a21);
  a20=(a20+a16);
  a01=(a01-a20);
  a36=(a36*a24);
  a01=(a01+a36);
  a36=(a29*a28);
  a01=(a01+a36);
  a36=(a26*a30);
  a01=(a01-a36);
  a36=(a31*a27);
  a01=(a01-a36);
  a35=(a35*a01);
  a34=(a34+a35);
  a35=(a11+a11);
  a34=(a34/a35);
  a10=(a10*a34);
  a33=(a33-a10);
  if (res[0]!=0) res[0][3]=a33;
  a01=(a01/a11);
  a12=(a12+a12);
  a12=(a12*a34);
  a01=(a01-a12);
  if (res[0]!=0) res[0][4]=a01;
  a39=(a39/a11);
  a13=(a13+a13);
  a13=(a13*a34);
  a39=(a39-a13);
  if (res[0]!=0) res[0][5]=a39;
  a37=(a37/a11);
  a14=(a14+a14);
  a14=(a14*a34);
  a37=(a37-a14);
  if (res[0]!=0) res[0][6]=a37;
  a37=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][7]=a37;
  a37=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][8]=a37;
  a37=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][9]=a37;
  a37=arg[3]? arg[3][35] : 0;
  a14=(a37*a26);
  a34=arg[1]? arg[1][11] : 0;
  a11=arg[3]? arg[3][34] : 0;
  a34=(a34/a11);
  a39=(a14*a34);
  a13=(a11*a29);
  a01=arg[1]? arg[1][12] : 0;
  a01=(a01/a37);
  a12=(a13*a01);
  a39=(a39-a12);
  a12=arg[3]? arg[3][33] : 0;
  a33=(a29*a01);
  a10=(a26*a34);
  a33=(a33-a10);
  a33=(a12*a33);
  a39=(a39+a33);
  a33=(a23*a28);
  a39=(a39-a33);
  a33=(a18*a30);
  a39=(a39+a33);
  a33=(a15*a32);
  a39=(a39+a33);
  a33=(a19*a27);
  a39=(a39-a33);
  if (res[0]!=0) res[0][10]=a39;
  a39=(a12*a31);
  a33=(a39*a01);
  a10=arg[1]? arg[1][10] : 0;
  a10=(a10/a12);
  a26=(a26*a10);
  a12=(a31*a01);
  a26=(a26-a12);
  a11=(a11*a26);
  a33=(a33+a11);
  a14=(a14*a10);
  a33=(a33-a14);
  a14=(a19*a28);
  a33=(a33+a14);
  a14=(a15*a30);
  a33=(a33+a14);
  a14=(a18*a32);
  a33=(a33-a14);
  a14=(a23*a27);
  a33=(a33-a14);
  if (res[0]!=0) res[0][11]=a33;
  a13=(a13*a10);
  a39=(a39*a34);
  a13=(a13-a39);
  a31=(a31*a34);
  a29=(a29*a10);
  a31=(a31-a29);
  a37=(a37*a31);
  a13=(a13+a37);
  a28=(a15*a28);
  a13=(a13+a28);
  a30=(a19*a30);
  a13=(a13-a30);
  a32=(a23*a32);
  a13=(a13+a32);
  a27=(a18*a27);
  a13=(a13-a27);
  if (res[0]!=0) res[0][12]=a13;
  a13=arg[3]? arg[3][25] : 0;
  a13=(a13*a01);
  a27=arg[3]? arg[3][17] : 0;
  a27=(a27*a34);
  a13=(a13+a27);
  a27=arg[3]? arg[3][9] : 0;
  a27=(a27*a10);
  a13=(a13+a27);
  a19=(a19*a40);
  a15=(a15*a22);
  a19=(a19+a15);
  a18=(a18*a38);
  a19=(a19+a18);
  a23=(a23*a25);
  a19=(a19+a23);
  a19=(a19/a09);
  a00=(a00*a19);
  a13=(a13+a00);
  if (res[0]!=0) res[0][13]=a13;
  a13=arg[3]? arg[3][26] : 0;
  a13=(a13*a01);
  a00=arg[3]? arg[3][18] : 0;
  a00=(a00*a34);
  a13=(a13+a00);
  a00=arg[3]? arg[3][10] : 0;
  a00=(a00*a10);
  a13=(a13+a00);
  a02=(a02*a19);
  a13=(a13+a02);
  if (res[0]!=0) res[0][14]=a13;
  a13=arg[3]? arg[3][27] : 0;
  a13=(a13*a01);
  a02=arg[3]? arg[3][19] : 0;
  a02=(a02*a34);
  a13=(a13+a02);
  a02=arg[3]? arg[3][11] : 0;
  a02=(a02*a10);
  a13=(a13+a02);
  a03=(a03*a19);
  a13=(a13+a03);
  if (res[0]!=0) res[0][15]=a13;
  a13=arg[3]? arg[3][28] : 0;
  a13=(a13*a01);
  a03=arg[3]? arg[3][20] : 0;
  a03=(a03*a34);
  a13=(a13+a03);
  a03=arg[3]? arg[3][12] : 0;
  a03=(a03*a10);
  a13=(a13+a03);
  a04=(a04*a19);
  a13=(a13+a04);
  if (res[0]!=0) res[0][16]=a13;
  a13=arg[3]? arg[3][29] : 0;
  a13=(a13*a01);
  a04=arg[3]? arg[3][21] : 0;
  a04=(a04*a34);
  a13=(a13+a04);
  a04=arg[3]? arg[3][13] : 0;
  a04=(a04*a10);
  a13=(a13+a04);
  a05=(a05*a19);
  a13=(a13+a05);
  if (res[0]!=0) res[0][17]=a13;
  a13=arg[3]? arg[3][30] : 0;
  a13=(a13*a01);
  a05=arg[3]? arg[3][22] : 0;
  a05=(a05*a34);
  a13=(a13+a05);
  a05=arg[3]? arg[3][14] : 0;
  a05=(a05*a10);
  a13=(a13+a05);
  a06=(a06*a19);
  a13=(a13+a06);
  if (res[0]!=0) res[0][18]=a13;
  a13=arg[3]? arg[3][31] : 0;
  a13=(a13*a01);
  a06=arg[3]? arg[3][23] : 0;
  a06=(a06*a34);
  a13=(a13+a06);
  a06=arg[3]? arg[3][15] : 0;
  a06=(a06*a10);
  a13=(a13+a06);
  a07=(a07*a19);
  a13=(a13+a07);
  if (res[0]!=0) res[0][19]=a13;
  a13=arg[3]? arg[3][32] : 0;
  a13=(a13*a01);
  a01=arg[3]? arg[3][24] : 0;
  a01=(a01*a34);
  a13=(a13+a01);
  a01=arg[3]? arg[3][16] : 0;
  a01=(a01*a10);
  a13=(a13+a01);
  a08=(a08*a19);
  a13=(a13+a08);
  if (res[0]!=0) res[0][20]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
