/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) multirotor_ode_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {63, 1, 1};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[23] = 
  {21, 5, 0, 3, 6, 9, 12, 15,
  15, 16, 17, 15, 16, 17, 15, 16,
  17, 15, 16, 17, 15, 16, 17};
static const casadi_int casadi_s6[3] = {5, 0, 1};

/* multirotor_ode_constr_h_fun_jac_uxt_zt:(i0[13],i1[8],i2[],i3[63])->(o0[5],o1[21x5,15nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16;
  a00=arg[3]? arg[3][43] : 0;
  a01=arg[0]? arg[0][7] : 0;
  a02=(a00*a01);
  a03=arg[3]? arg[3][44] : 0;
  a04=arg[0]? arg[0][8] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=arg[3]? arg[3][45] : 0;
  a06=arg[0]? arg[0][9] : 0;
  a07=(a05*a06);
  a02=(a02+a07);
  a07=arg[3]? arg[3][58] : 0;
  a02=(a02-a07);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[3]? arg[3][46] : 0;
  a07=(a02*a01);
  a08=arg[3]? arg[3][47] : 0;
  a09=(a08*a04);
  a07=(a07+a09);
  a09=arg[3]? arg[3][48] : 0;
  a10=(a09*a06);
  a07=(a07+a10);
  a10=arg[3]? arg[3][59] : 0;
  a07=(a07-a10);
  if (res[0]!=0) res[0][1]=a07;
  a07=arg[3]? arg[3][49] : 0;
  a10=(a07*a01);
  a11=arg[3]? arg[3][50] : 0;
  a12=(a11*a04);
  a10=(a10+a12);
  a12=arg[3]? arg[3][51] : 0;
  a13=(a12*a06);
  a10=(a10+a13);
  a13=arg[3]? arg[3][60] : 0;
  a10=(a10-a13);
  if (res[0]!=0) res[0][2]=a10;
  a10=arg[3]? arg[3][52] : 0;
  a13=(a10*a01);
  a14=arg[3]? arg[3][53] : 0;
  a15=(a14*a04);
  a13=(a13+a15);
  a15=arg[3]? arg[3][54] : 0;
  a16=(a15*a06);
  a13=(a13+a16);
  a16=arg[3]? arg[3][61] : 0;
  a13=(a13-a16);
  if (res[0]!=0) res[0][3]=a13;
  a13=arg[3]? arg[3][55] : 0;
  a01=(a13*a01);
  a16=arg[3]? arg[3][56] : 0;
  a04=(a16*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][57] : 0;
  a06=(a04*a06);
  a01=(a01+a06);
  a06=arg[3]? arg[3][62] : 0;
  a01=(a01-a06);
  if (res[0]!=0) res[0][4]=a01;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a03;
  if (res[1]!=0) res[1][2]=a05;
  if (res[1]!=0) res[1][3]=a02;
  if (res[1]!=0) res[1][4]=a08;
  if (res[1]!=0) res[1][5]=a09;
  if (res[1]!=0) res[1][6]=a07;
  if (res[1]!=0) res[1][7]=a11;
  if (res[1]!=0) res[1][8]=a12;
  if (res[1]!=0) res[1][9]=a10;
  if (res[1]!=0) res[1][10]=a14;
  if (res[1]!=0) res[1][11]=a15;
  if (res[1]!=0) res[1][12]=a13;
  if (res[1]!=0) res[1][13]=a16;
  if (res[1]!=0) res[1][14]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int multirotor_ode_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int multirotor_ode_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int multirotor_ode_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multirotor_ode_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int multirotor_ode_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multirotor_ode_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void multirotor_ode_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void multirotor_ode_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int multirotor_ode_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int multirotor_ode_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real multirotor_ode_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multirotor_ode_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multirotor_ode_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multirotor_ode_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multirotor_ode_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int multirotor_ode_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int multirotor_ode_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
