/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {20, 1, 1};
static const casadi_int casadi_s3[3] = {17, 1, 1};

/* quadrotor_ode_expl_vde_adj:(i0[13],i1[13],i2[4],i3[20])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[2]? arg[2][0] : 0;
  a01=arg[2]? arg[2][1] : 0;
  a00=(a00+a01);
  a01=arg[2]? arg[2][2] : 0;
  a00=(a00+a01);
  a01=arg[2]? arg[2][3] : 0;
  a00=(a00+a01);
  a01=arg[3]? arg[3][0] : 0;
  a00=(a00/a01);
  a02=arg[0]? arg[0][3] : 0;
  a03=casadi_sq(a02);
  a04=arg[0]? arg[0][4] : 0;
  a05=casadi_sq(a04);
  a03=(a03+a05);
  a05=arg[0]? arg[0][5] : 0;
  a06=casadi_sq(a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][6] : 0;
  a07=casadi_sq(a06);
  a03=(a03+a07);
  a03=sqrt(a03);
  a07=(a02/a03);
  a08=(a00*a07);
  a09=arg[1]? arg[1][9] : 0;
  a10=(a08*a09);
  a11=(a04/a03);
  a12=(a00*a11);
  a13=arg[1]? arg[1][8] : 0;
  a14=(a12*a13);
  a10=(a10-a14);
  a14=(a07*a09);
  a15=(a11*a13);
  a14=(a14-a15);
  a15=(a05/a03);
  a16=arg[1]? arg[1][7] : 0;
  a17=(a15*a16);
  a14=(a14+a17);
  a17=(a00*a14);
  a10=(a10+a17);
  a17=(a00*a15);
  a18=(a17*a16);
  a10=(a10+a18);
  a18=arg[0]? arg[0][12] : 0;
  a19=5.0000000000000000e-01;
  a20=arg[1]? arg[1][6] : 0;
  a20=(a19*a20);
  a21=(a18*a20);
  a10=(a10+a21);
  a21=arg[0]? arg[0][11] : 0;
  a22=arg[1]? arg[1][5] : 0;
  a22=(a19*a22);
  a23=(a21*a22);
  a10=(a10+a23);
  a23=arg[0]? arg[0][10] : 0;
  a24=arg[1]? arg[1][4] : 0;
  a24=(a19*a24);
  a25=(a23*a24);
  a10=(a10+a25);
  a25=arg[0]? arg[0][8] : 0;
  a26=(a25*a11);
  a27=arg[0]? arg[0][7] : 0;
  a28=(a27*a15);
  a26=(a26-a28);
  a28=arg[0]? arg[0][9] : 0;
  a29=(a28*a07);
  a26=(a26+a29);
  a29=arg[1]? arg[1][2] : 0;
  a30=(a26*a29);
  a10=(a10+a30);
  a30=(a25*a07);
  a31=(a06/a03);
  a32=(a27*a31);
  a30=(a30+a32);
  a32=(a28*a11);
  a30=(a30-a32);
  a32=arg[1]? arg[1][1] : 0;
  a33=(a30*a32);
  a10=(a10+a33);
  a33=(a11*a29);
  a34=(a07*a32);
  a33=(a33+a34);
  a34=arg[1]? arg[1][0] : 0;
  a35=(a31*a34);
  a33=(a33-a35);
  a35=(a25*a33);
  a10=(a10+a35);
  a35=(a07*a29);
  a36=(a11*a32);
  a35=(a35-a36);
  a36=(a15*a34);
  a35=(a35+a36);
  a36=(a28*a35);
  a10=(a10+a36);
  a36=(a27*a07);
  a37=(a25*a31);
  a36=(a36-a37);
  a37=(a28*a15);
  a36=(a36+a37);
  a37=(a36*a34);
  a10=(a10+a37);
  a37=(a31*a32);
  a38=(a15*a29);
  a37=(a37-a38);
  a38=(a07*a34);
  a37=(a37+a38);
  a38=(a27*a37);
  a10=(a10+a38);
  a38=(a10/a03);
  a02=(a02+a02);
  a39=(a11/a03);
  a40=(a31*a16);
  a41=(a11*a09);
  a42=(a07*a13);
  a41=(a41+a42);
  a40=(a40-a41);
  a41=(a00*a40);
  a42=(a12*a09);
  a43=(a08*a13);
  a42=(a42+a43);
  a41=(a41-a42);
  a42=(a00*a31);
  a43=(a42*a16);
  a41=(a41+a43);
  a43=(a21*a20);
  a41=(a41+a43);
  a43=(a18*a22);
  a41=(a41-a43);
  a43=arg[1]? arg[1][3] : 0;
  a19=(a19*a43);
  a43=(a23*a19);
  a41=(a41-a43);
  a43=(a30*a29);
  a41=(a41+a43);
  a43=(a26*a32);
  a41=(a41-a43);
  a43=(a28*a33);
  a41=(a41-a43);
  a43=(a25*a35);
  a41=(a41+a43);
  a43=(a27*a11);
  a44=(a25*a15);
  a43=(a43+a44);
  a44=(a28*a31);
  a43=(a43+a44);
  a44=(a43*a34);
  a41=(a41+a44);
  a44=(a31*a29);
  a45=(a15*a32);
  a44=(a44+a45);
  a45=(a11*a34);
  a44=(a44+a45);
  a45=(a27*a44);
  a41=(a41+a45);
  a39=(a39*a41);
  a45=(a15/a03);
  a46=(a42*a13);
  a47=(a17*a09);
  a46=(a46-a47);
  a08=(a08*a16);
  a46=(a46+a08);
  a08=(a31*a13);
  a47=(a15*a09);
  a08=(a08-a47);
  a47=(a07*a16);
  a08=(a08+a47);
  a47=(a00*a08);
  a46=(a46+a47);
  a47=(a23*a20);
  a46=(a46-a47);
  a47=(a18*a24);
  a46=(a46+a47);
  a47=(a21*a19);
  a46=(a46-a47);
  a47=(a36*a29);
  a46=(a46-a47);
  a47=(a43*a32);
  a46=(a46+a47);
  a26=(a26*a34);
  a46=(a46+a26);
  a26=(a27*a35);
  a46=(a46-a26);
  a26=(a25*a44);
  a46=(a46+a26);
  a26=(a28*a37);
  a46=(a46+a26);
  a45=(a45*a46);
  a39=(a39+a45);
  a45=(a31/a03);
  a42=(a42*a09);
  a17=(a17*a13);
  a42=(a42+a17);
  a12=(a12*a16);
  a42=(a42+a12);
  a09=(a31*a09);
  a13=(a15*a13);
  a09=(a09+a13);
  a16=(a11*a16);
  a09=(a09+a16);
  a00=(a00*a09);
  a42=(a42+a00);
  a00=(a23*a22);
  a42=(a42+a00);
  a00=(a21*a24);
  a42=(a42-a00);
  a00=(a18*a19);
  a42=(a42-a00);
  a43=(a43*a29);
  a42=(a42+a43);
  a36=(a36*a32);
  a42=(a42+a36);
  a30=(a30*a34);
  a42=(a42-a30);
  a27=(a27*a33);
  a42=(a42+a27);
  a28=(a28*a44);
  a42=(a42+a28);
  a25=(a25*a37);
  a42=(a42-a25);
  a45=(a45*a42);
  a39=(a39+a45);
  a45=(a07/a03);
  a45=(a45*a10);
  a39=(a39+a45);
  a45=(a03+a03);
  a39=(a39/a45);
  a02=(a02*a39);
  a38=(a38-a02);
  if (res[0]!=0) res[0][3]=a38;
  a41=(a41/a03);
  a04=(a04+a04);
  a04=(a04*a39);
  a41=(a41-a04);
  if (res[0]!=0) res[0][4]=a41;
  a46=(a46/a03);
  a05=(a05+a05);
  a05=(a05*a39);
  a46=(a46-a05);
  if (res[0]!=0) res[0][5]=a46;
  a42=(a42/a03);
  a06=(a06+a06);
  a06=(a06*a39);
  a42=(a42-a06);
  if (res[0]!=0) res[0][6]=a42;
  a42=(a31*a33);
  a06=(a15*a35);
  a42=(a42-a06);
  a06=(a11*a44);
  a42=(a42+a06);
  a06=(a07*a37);
  a42=(a42+a06);
  if (res[0]!=0) res[0][7]=a42;
  a42=(a07*a33);
  a06=(a11*a35);
  a42=(a42+a06);
  a06=(a15*a44);
  a42=(a42+a06);
  a06=(a31*a37);
  a42=(a42-a06);
  if (res[0]!=0) res[0][8]=a42;
  a35=(a07*a35);
  a33=(a11*a33);
  a35=(a35-a33);
  a44=(a31*a44);
  a35=(a35+a44);
  a37=(a15*a37);
  a35=(a35+a37);
  if (res[0]!=0) res[0][9]=a35;
  a35=arg[3]? arg[3][11] : 0;
  a37=(a35*a18);
  a44=arg[1]? arg[1][11] : 0;
  a33=arg[3]? arg[3][10] : 0;
  a44=(a44/a33);
  a42=(a37*a44);
  a06=(a33*a21);
  a39=arg[1]? arg[1][12] : 0;
  a39=(a39/a35);
  a03=(a06*a39);
  a42=(a42-a03);
  a03=arg[3]? arg[3][9] : 0;
  a46=(a21*a39);
  a05=(a18*a44);
  a46=(a46-a05);
  a46=(a03*a46);
  a42=(a42+a46);
  a46=(a15*a20);
  a42=(a42-a46);
  a46=(a31*a22);
  a42=(a42+a46);
  a46=(a07*a24);
  a42=(a42+a46);
  a46=(a11*a19);
  a42=(a42-a46);
  if (res[0]!=0) res[0][10]=a42;
  a42=(a03*a23);
  a46=(a42*a39);
  a05=arg[1]? arg[1][10] : 0;
  a05=(a05/a03);
  a18=(a18*a05);
  a03=(a23*a39);
  a18=(a18-a03);
  a33=(a33*a18);
  a46=(a46+a33);
  a37=(a37*a05);
  a46=(a46-a37);
  a37=(a11*a20);
  a46=(a46+a37);
  a37=(a07*a22);
  a46=(a46+a37);
  a37=(a31*a24);
  a46=(a46-a37);
  a37=(a15*a19);
  a46=(a46-a37);
  if (res[0]!=0) res[0][11]=a46;
  a06=(a06*a05);
  a42=(a42*a44);
  a06=(a06-a42);
  a23=(a23*a44);
  a21=(a21*a05);
  a23=(a23-a21);
  a35=(a35*a23);
  a06=(a06+a35);
  a20=(a07*a20);
  a06=(a06+a20);
  a22=(a11*a22);
  a06=(a06-a22);
  a24=(a15*a24);
  a06=(a06+a24);
  a19=(a31*a19);
  a06=(a06-a19);
  if (res[0]!=0) res[0][12]=a06;
  a06=arg[3]? arg[3][2] : 0;
  a06=(a06*a05);
  a19=arg[3]? arg[3][12] : 0;
  a19=(a19*a39);
  a39=arg[3]? arg[3][1] : 0;
  a39=(a39*a44);
  a39=(a19+a39);
  a06=(a06-a39);
  a11=(a11*a40);
  a07=(a07*a14);
  a11=(a11+a07);
  a31=(a31*a09);
  a11=(a11+a31);
  a15=(a15*a08);
  a11=(a11+a15);
  a11=(a11/a01);
  a06=(a06+a11);
  if (res[0]!=0) res[0][13]=a06;
  a06=arg[3]? arg[3][4] : 0;
  a06=(a06*a05);
  a01=arg[3]? arg[3][3] : 0;
  a01=(a01*a44);
  a01=(a19+a01);
  a06=(a06-a01);
  a06=(a06+a11);
  if (res[0]!=0) res[0][14]=a06;
  a06=arg[3]? arg[3][5] : 0;
  a06=(a06*a44);
  a06=(a19-a06);
  a01=arg[3]? arg[3][6] : 0;
  a01=(a01*a05);
  a06=(a06+a01);
  a06=(a06+a11);
  if (res[0]!=0) res[0][15]=a06;
  a06=arg[3]? arg[3][7] : 0;
  a06=(a06*a44);
  a19=(a19-a06);
  a06=arg[3]? arg[3][8] : 0;
  a06=(a06*a05);
  a19=(a19+a06);
  a19=(a19+a11);
  if (res[0]!=0) res[0][16]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
