/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_ode_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 0, 1};
static const casadi_int casadi_s2[3] = {12, 1, 1};
static const casadi_int casadi_s3[3] = {43, 1, 1};
static const casadi_int casadi_s4[32] = 
  {13, 13, 0, 0, 0, 0, 4, 8,
  12, 16, 16, 16, 16, 16, 16, 16,
  3, 4, 5, 6, 3, 4, 5, 6,
  3, 4, 5, 6, 3, 4, 5, 6};

/* quadrotor_ode_cost_y_e_hess:(i0[13],i1[],i2[],i3[12],i4[],i5[43])->(o0[13x13,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  a00=arg[5]? arg[5][42] : 0;
  a01=arg[3]? arg[3][4] : 0;
  a02=arg[0]? arg[0][3] : 0;
  a03=casadi_sq(a02);
  a04=arg[0]? arg[0][4] : 0;
  a05=casadi_sq(a04);
  a03=(a03+a05);
  a05=arg[0]? arg[0][5] : 0;
  a06=casadi_sq(a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][6] : 0;
  a07=casadi_sq(a06);
  a03=(a03+a07);
  a03=sqrt(a03);
  a07=(a02/a03);
  a08=arg[5]? arg[5][39] : 0;
  a09=(a07*a08);
  a10=(a04/a03);
  a11=arg[5]? arg[5][40] : 0;
  a12=(a10*a11);
  a09=(a09+a12);
  a12=(a05/a03);
  a13=arg[5]? arg[5][41] : 0;
  a14=(a12*a13);
  a09=(a09+a14);
  a14=(a06/a03);
  a15=(a14*a00);
  a09=(a09+a15);
  a15=casadi_sq(a09);
  a16=(a12*a11);
  a17=(a14*a08);
  a16=(a16-a17);
  a17=(a10*a13);
  a16=(a16-a17);
  a17=(a07*a00);
  a16=(a16+a17);
  a17=casadi_sq(a16);
  a15=(a15+a17);
  a17=1.0000000000000000e-03;
  a15=(a15+a17);
  a15=sqrt(a15);
  a17=(a01/a15);
  a18=(1./a03);
  a19=(a07/a03);
  a20=(a19*a07);
  a20=(a18-a20);
  a21=(a11*a20);
  a22=(a10/a03);
  a23=(a22*a07);
  a24=(a08*a23);
  a21=(a21+a24);
  a24=(a14/a03);
  a25=(a24*a07);
  a26=(a13*a25);
  a21=(a21-a26);
  a26=(a12/a03);
  a27=(a26*a07);
  a28=(a00*a27);
  a21=(a21+a28);
  a28=(a17*a21);
  a29=(a07*a11);
  a30=(a10*a08);
  a29=(a29-a30);
  a30=(a14*a13);
  a29=(a29+a30);
  a30=(a12*a00);
  a29=(a29-a30);
  a30=(a17/a15);
  a31=(a09+a09);
  a32=(a08*a20);
  a33=(a11*a23);
  a32=(a32-a33);
  a33=(a13*a27);
  a32=(a32-a33);
  a33=(a00*a25);
  a32=(a32-a33);
  a33=(a31*a32);
  a34=(a16+a16);
  a35=(a08*a25);
  a36=(a11*a27);
  a35=(a35-a36);
  a36=(a13*a23);
  a35=(a35+a36);
  a36=(a00*a20);
  a35=(a35+a36);
  a36=(a34*a35);
  a33=(a33+a36);
  a36=(a15+a15);
  a33=(a33/a36);
  a37=(a30*a33);
  a38=(a29*a37);
  a28=(a28-a38);
  a38=arg[3]? arg[3][5] : 0;
  a39=(a38/a15);
  a40=(a39/a15);
  a41=(a40*a33);
  a28=(a28-a41);
  a41=(a16/a15);
  a41=(a41/a15);
  a42=(a41*a38);
  a43=(a07*a13);
  a44=(a12*a08);
  a45=(a14*a11);
  a44=(a44+a45);
  a43=(a43-a44);
  a44=(a10*a00);
  a43=(a43+a44);
  a44=(a09*a43);
  a45=(a29*a16);
  a44=(a44+a45);
  a44=(a44/a15);
  a44=(a44/a15);
  a45=(a44*a01);
  a42=(a42+a45);
  a45=(a09*a29);
  a46=(a43*a16);
  a45=(a45-a46);
  a45=(a45/a15);
  a45=(a45/a15);
  a46=arg[3]? arg[3][3] : 0;
  a47=(a45*a46);
  a42=(a42+a47);
  a42=(a42/a36);
  a47=(a35+a35);
  a47=(a42*a47);
  a48=(a35/a15);
  a49=(a41*a33);
  a48=(a48-a49);
  a48=(a48/a15);
  a49=(a41/a15);
  a50=(a49*a33);
  a48=(a48-a50);
  a48=(a38*a48);
  a50=(a43*a32);
  a51=(a13*a20);
  a52=(a08*a27);
  a53=(a11*a25);
  a52=(a52+a53);
  a51=(a51+a52);
  a52=(a00*a23);
  a51=(a51-a52);
  a52=(a09*a51);
  a50=(a50+a52);
  a52=(a16*a21);
  a53=(a29*a35);
  a52=(a52+a53);
  a50=(a50+a52);
  a50=(a50/a15);
  a52=(a44*a33);
  a50=(a50-a52);
  a50=(a50/a15);
  a52=(a44/a15);
  a53=(a52*a33);
  a50=(a50-a53);
  a50=(a01*a50);
  a48=(a48+a50);
  a50=(a29*a32);
  a53=(a09*a21);
  a50=(a50+a53);
  a53=(a16*a51);
  a54=(a43*a35);
  a53=(a53+a54);
  a50=(a50-a53);
  a50=(a50/a15);
  a53=(a45*a33);
  a50=(a50-a53);
  a50=(a50/a15);
  a53=(a45/a15);
  a54=(a53*a33);
  a50=(a50-a54);
  a50=(a46*a50);
  a48=(a48+a50);
  a48=(a48/a36);
  a50=(a42/a36);
  a54=(a33+a33);
  a54=(a50*a54);
  a48=(a48-a54);
  a54=(a34*a48);
  a47=(a47+a54);
  a28=(a28-a47);
  a47=(a46/a15);
  a54=(a47*a51);
  a55=(a47/a15);
  a33=(a55*a33);
  a56=(a43*a33);
  a54=(a54-a56);
  a28=(a28-a54);
  a54=(a00*a28);
  a56=(a17*a32);
  a57=(a09*a37);
  a56=(a56-a57);
  a57=(a47*a35);
  a58=(a16*a33);
  a57=(a57-a58);
  a56=(a56-a57);
  a57=(a13*a56);
  a54=(a54+a57);
  a35=(a17*a35);
  a57=(a16*a37);
  a35=(a35-a57);
  a57=(a47*a32);
  a58=(a09*a33);
  a57=(a57-a58);
  a35=(a35+a57);
  a57=(a11*a35);
  a54=(a54+a57);
  a51=(a17*a51);
  a37=(a43*a37);
  a51=(a51-a37);
  a32=(a32+a32);
  a32=(a42*a32);
  a48=(a31*a48);
  a32=(a32+a48);
  a51=(a51-a32);
  a21=(a47*a21);
  a33=(a29*a33);
  a21=(a21-a33);
  a51=(a51+a21);
  a21=(a08*a51);
  a54=(a54+a21);
  a21=(a54/a03);
  a33=(a29*a17);
  a39=(a39+a33);
  a33=(a34*a42);
  a39=(a39-a33);
  a33=(a43*a47);
  a39=(a39-a33);
  a33=(a00*a39);
  a32=(a09*a17);
  a48=(a16*a47);
  a32=(a32-a48);
  a48=(a13*a32);
  a33=(a33+a48);
  a48=(a16*a17);
  a37=(a09*a47);
  a48=(a48+a37);
  a37=(a11*a48);
  a33=(a33+a37);
  a37=(a43*a17);
  a57=(a31*a42);
  a37=(a37-a57);
  a57=(a29*a47);
  a37=(a37+a57);
  a57=(a08*a37);
  a33=(a33+a57);
  a57=(a33/a03);
  a57=(a57/a03);
  a58=(a57*a07);
  a21=(a21-a58);
  a58=2.;
  a59=(a13*a48);
  a60=(a08*a39);
  a61=(a11*a32);
  a60=(a60+a61);
  a59=(a59-a60);
  a60=(a00*a37);
  a59=(a59+a60);
  a60=(a24*a59);
  a61=(a11*a39);
  a62=(a08*a32);
  a61=(a61-a62);
  a62=(a00*a48);
  a61=(a61-a62);
  a62=(a13*a37);
  a61=(a61+a62);
  a62=(a26*a61);
  a60=(a60+a62);
  a32=(a00*a32);
  a39=(a13*a39);
  a32=(a32-a39);
  a48=(a08*a48);
  a32=(a32-a48);
  a37=(a11*a37);
  a32=(a32+a37);
  a37=(a22*a32);
  a60=(a60+a37);
  a37=(a19*a33);
  a60=(a60+a37);
  a37=(a03+a03);
  a60=(a60/a37);
  a58=(a58*a60);
  a02=(a02+a02);
  a48=(a13*a35);
  a39=(a08*a28);
  a62=(a11*a56);
  a39=(a39+a62);
  a48=(a48-a39);
  a39=(a00*a51);
  a48=(a48+a39);
  a48=(a24*a48);
  a25=(a25/a03);
  a39=(a24/a03);
  a62=(a39*a07);
  a25=(a25+a62);
  a25=(a59*a25);
  a48=(a48-a25);
  a25=(a11*a28);
  a62=(a08*a56);
  a25=(a25-a62);
  a62=(a00*a35);
  a25=(a25-a62);
  a62=(a13*a51);
  a25=(a25+a62);
  a25=(a26*a25);
  a27=(a27/a03);
  a62=(a26/a03);
  a63=(a62*a07);
  a27=(a27+a63);
  a27=(a61*a27);
  a25=(a25-a27);
  a48=(a48+a25);
  a56=(a00*a56);
  a28=(a13*a28);
  a56=(a56-a28);
  a35=(a08*a35);
  a56=(a56-a35);
  a51=(a11*a51);
  a56=(a56+a51);
  a56=(a22*a56);
  a23=(a23/a03);
  a51=(a22/a03);
  a35=(a51*a07);
  a23=(a23+a35);
  a23=(a32*a23);
  a56=(a56-a23);
  a48=(a48+a56);
  a20=(a20/a03);
  a56=(a19/a03);
  a23=(a56*a07);
  a20=(a20-a23);
  a20=(a33*a20);
  a54=(a19*a54);
  a20=(a20+a54);
  a48=(a48+a20);
  a48=(a48/a37);
  a60=(a60/a37);
  a07=(a07+a07);
  a07=(a60*a07);
  a48=(a48-a07);
  a48=(a02*a48);
  a48=(a58+a48);
  a21=(a21-a48);
  if (res[0]!=0) res[0][0]=a21;
  a21=(a26*a10);
  a48=(a00*a21);
  a07=(a19*a10);
  a20=(a11*a07);
  a54=(a22*a10);
  a54=(a18-a54);
  a23=(a08*a54);
  a20=(a20+a23);
  a23=(a24*a10);
  a35=(a13*a23);
  a20=(a20+a35);
  a48=(a48-a20);
  a20=(a17*a48);
  a35=(a11*a54);
  a28=(a08*a07);
  a35=(a35-a28);
  a28=(a13*a21);
  a35=(a35-a28);
  a28=(a00*a23);
  a35=(a35-a28);
  a28=(a31*a35);
  a25=(a08*a23);
  a27=(a11*a21);
  a25=(a25-a27);
  a27=(a13*a54);
  a25=(a25-a27);
  a27=(a00*a07);
  a25=(a25-a27);
  a27=(a34*a25);
  a28=(a28+a27);
  a28=(a28/a36);
  a27=(a30*a28);
  a63=(a29*a27);
  a20=(a20-a63);
  a63=(a40*a28);
  a20=(a20-a63);
  a63=(a25+a25);
  a63=(a42*a63);
  a64=(a25/a15);
  a65=(a41*a28);
  a64=(a64-a65);
  a64=(a64/a15);
  a65=(a49*a28);
  a64=(a64-a65);
  a64=(a38*a64);
  a65=(a43*a35);
  a66=(a08*a21);
  a67=(a11*a23);
  a66=(a66+a67);
  a67=(a13*a07);
  a66=(a66-a67);
  a67=(a00*a54);
  a66=(a66+a67);
  a67=(a09*a66);
  a65=(a65+a67);
  a67=(a16*a48);
  a68=(a29*a25);
  a67=(a67+a68);
  a65=(a65+a67);
  a65=(a65/a15);
  a67=(a44*a28);
  a65=(a65-a67);
  a65=(a65/a15);
  a67=(a52*a28);
  a65=(a65-a67);
  a65=(a01*a65);
  a64=(a64+a65);
  a65=(a29*a35);
  a67=(a09*a48);
  a65=(a65+a67);
  a67=(a16*a66);
  a68=(a43*a25);
  a67=(a67+a68);
  a65=(a65-a67);
  a65=(a65/a15);
  a67=(a45*a28);
  a65=(a65-a67);
  a65=(a65/a15);
  a67=(a53*a28);
  a65=(a65-a67);
  a65=(a46*a65);
  a64=(a64+a65);
  a64=(a64/a36);
  a65=(a28+a28);
  a65=(a50*a65);
  a64=(a64-a65);
  a65=(a34*a64);
  a63=(a63+a65);
  a20=(a20-a63);
  a63=(a47*a66);
  a28=(a55*a28);
  a65=(a43*a28);
  a63=(a63-a65);
  a20=(a20-a63);
  a63=(a00*a20);
  a65=(a17*a35);
  a67=(a09*a27);
  a65=(a65-a67);
  a67=(a47*a25);
  a68=(a16*a28);
  a67=(a67-a68);
  a65=(a65-a67);
  a67=(a13*a65);
  a63=(a63+a67);
  a25=(a17*a25);
  a67=(a16*a27);
  a25=(a25-a67);
  a67=(a47*a35);
  a68=(a09*a28);
  a67=(a67-a68);
  a25=(a25+a67);
  a67=(a11*a25);
  a63=(a63+a67);
  a66=(a17*a66);
  a27=(a43*a27);
  a66=(a66-a27);
  a35=(a35+a35);
  a35=(a42*a35);
  a64=(a31*a64);
  a35=(a35+a64);
  a66=(a66-a35);
  a48=(a47*a48);
  a28=(a29*a28);
  a48=(a48-a28);
  a66=(a66+a48);
  a48=(a08*a66);
  a63=(a63+a48);
  a48=(a63/a03);
  a28=(a57*a10);
  a48=(a48-a28);
  a28=(a13*a25);
  a35=(a08*a20);
  a64=(a11*a65);
  a35=(a35+a64);
  a28=(a28-a35);
  a35=(a00*a66);
  a28=(a28+a35);
  a28=(a24*a28);
  a23=(a23/a03);
  a35=(a39*a10);
  a23=(a23+a35);
  a23=(a59*a23);
  a28=(a28-a23);
  a23=(a11*a20);
  a35=(a08*a65);
  a23=(a23-a35);
  a35=(a00*a25);
  a23=(a23-a35);
  a35=(a13*a66);
  a23=(a23+a35);
  a23=(a26*a23);
  a21=(a21/a03);
  a35=(a62*a10);
  a21=(a21+a35);
  a21=(a61*a21);
  a23=(a23-a21);
  a28=(a28+a23);
  a54=(a54/a03);
  a23=(a51*a10);
  a54=(a54-a23);
  a54=(a32*a54);
  a65=(a00*a65);
  a20=(a13*a20);
  a65=(a65-a20);
  a25=(a08*a25);
  a65=(a65-a25);
  a66=(a11*a66);
  a65=(a65+a66);
  a66=(a22*a65);
  a54=(a54+a66);
  a28=(a28+a54);
  a63=(a19*a63);
  a07=(a07/a03);
  a54=(a56*a10);
  a07=(a07+a54);
  a07=(a33*a07);
  a63=(a63-a07);
  a28=(a28+a63);
  a28=(a28/a37);
  a63=(a10+a10);
  a63=(a60*a63);
  a28=(a28-a63);
  a63=(a02*a28);
  a48=(a48-a63);
  if (res[0]!=0) res[0][1]=a48;
  a63=(a22*a12);
  a07=(a08*a63);
  a54=(a19*a12);
  a66=(a11*a54);
  a07=(a07-a66);
  a66=(a24*a12);
  a25=(a13*a66);
  a07=(a07-a25);
  a25=(a26*a12);
  a25=(a18-a25);
  a20=(a00*a25);
  a07=(a07-a20);
  a20=(a17*a07);
  a23=(a13*a25);
  a21=(a08*a54);
  a35=(a11*a63);
  a21=(a21+a35);
  a23=(a23-a21);
  a21=(a00*a66);
  a23=(a23-a21);
  a21=(a31*a23);
  a35=(a11*a25);
  a64=(a08*a66);
  a35=(a35+a64);
  a64=(a13*a63);
  a35=(a35+a64);
  a64=(a00*a54);
  a35=(a35-a64);
  a64=(a34*a35);
  a21=(a21+a64);
  a21=(a21/a36);
  a64=(a30*a21);
  a27=(a29*a64);
  a20=(a20-a27);
  a27=(a40*a21);
  a20=(a20-a27);
  a27=(a35+a35);
  a27=(a42*a27);
  a67=(a35/a15);
  a68=(a41*a21);
  a67=(a67-a68);
  a67=(a67/a15);
  a68=(a49*a21);
  a67=(a67-a68);
  a67=(a38*a67);
  a68=(a43*a23);
  a69=(a13*a54);
  a70=(a08*a25);
  a71=(a11*a66);
  a70=(a70-a71);
  a69=(a69+a70);
  a70=(a00*a63);
  a69=(a69+a70);
  a70=(a09*a69);
  a68=(a68-a70);
  a70=(a16*a07);
  a71=(a29*a35);
  a70=(a70+a71);
  a68=(a68+a70);
  a68=(a68/a15);
  a70=(a44*a21);
  a68=(a68-a70);
  a68=(a68/a15);
  a70=(a52*a21);
  a68=(a68-a70);
  a68=(a01*a68);
  a67=(a67+a68);
  a68=(a29*a23);
  a70=(a09*a07);
  a68=(a68+a70);
  a70=(a43*a35);
  a71=(a16*a69);
  a70=(a70-a71);
  a68=(a68-a70);
  a68=(a68/a15);
  a70=(a45*a21);
  a68=(a68-a70);
  a68=(a68/a15);
  a70=(a53*a21);
  a68=(a68-a70);
  a68=(a46*a68);
  a67=(a67+a68);
  a67=(a67/a36);
  a68=(a21+a21);
  a68=(a50*a68);
  a67=(a67-a68);
  a68=(a34*a67);
  a27=(a27+a68);
  a20=(a20-a27);
  a27=(a47*a69);
  a21=(a55*a21);
  a68=(a43*a21);
  a27=(a27+a68);
  a20=(a20+a27);
  a27=(a00*a20);
  a68=(a17*a23);
  a70=(a09*a64);
  a68=(a68-a70);
  a70=(a47*a35);
  a71=(a16*a21);
  a70=(a70-a71);
  a68=(a68-a70);
  a70=(a13*a68);
  a27=(a27+a70);
  a35=(a17*a35);
  a70=(a16*a64);
  a35=(a35-a70);
  a70=(a47*a23);
  a71=(a09*a21);
  a70=(a70-a71);
  a35=(a35+a70);
  a70=(a11*a35);
  a27=(a27+a70);
  a07=(a47*a07);
  a21=(a29*a21);
  a07=(a07-a21);
  a69=(a17*a69);
  a64=(a43*a64);
  a69=(a69+a64);
  a23=(a23+a23);
  a23=(a42*a23);
  a67=(a31*a67);
  a23=(a23+a67);
  a69=(a69+a23);
  a07=(a07-a69);
  a69=(a08*a07);
  a27=(a27+a69);
  a69=(a27/a03);
  a23=(a57*a12);
  a69=(a69-a23);
  a23=(a13*a35);
  a67=(a08*a20);
  a64=(a11*a68);
  a67=(a67+a64);
  a23=(a23-a67);
  a67=(a00*a07);
  a23=(a23+a67);
  a23=(a24*a23);
  a66=(a66/a03);
  a67=(a39*a12);
  a66=(a66+a67);
  a66=(a59*a66);
  a23=(a23-a66);
  a25=(a25/a03);
  a66=(a62*a12);
  a25=(a25-a66);
  a25=(a61*a25);
  a66=(a11*a20);
  a67=(a08*a68);
  a66=(a66-a67);
  a67=(a00*a35);
  a66=(a66-a67);
  a67=(a13*a07);
  a66=(a66+a67);
  a67=(a26*a66);
  a25=(a25+a67);
  a23=(a23+a25);
  a68=(a00*a68);
  a20=(a13*a20);
  a68=(a68-a20);
  a35=(a08*a35);
  a68=(a68-a35);
  a07=(a11*a07);
  a68=(a68+a07);
  a07=(a22*a68);
  a63=(a63/a03);
  a35=(a51*a12);
  a63=(a63+a35);
  a63=(a32*a63);
  a07=(a07-a63);
  a23=(a23+a07);
  a27=(a19*a27);
  a54=(a54/a03);
  a07=(a56*a12);
  a54=(a54+a07);
  a54=(a33*a54);
  a27=(a27-a54);
  a23=(a23+a27);
  a23=(a23/a37);
  a27=(a12+a12);
  a27=(a60*a27);
  a23=(a23-a27);
  a27=(a02*a23);
  a69=(a69-a27);
  if (res[0]!=0) res[0][2]=a69;
  a27=(a22*a14);
  a54=(a08*a27);
  a07=(a19*a14);
  a63=(a11*a07);
  a54=(a54-a63);
  a63=(a24*a14);
  a18=(a18-a63);
  a63=(a13*a18);
  a54=(a54+a63);
  a63=(a26*a14);
  a35=(a00*a63);
  a54=(a54+a35);
  a35=(a17*a54);
  a20=(a00*a18);
  a25=(a08*a07);
  a67=(a11*a27);
  a25=(a25+a67);
  a67=(a13*a63);
  a25=(a25+a67);
  a20=(a20-a25);
  a25=(a31*a20);
  a67=(a13*a27);
  a64=(a11*a63);
  a21=(a08*a18);
  a64=(a64+a21);
  a67=(a67-a64);
  a64=(a00*a07);
  a67=(a67-a64);
  a64=(a34*a67);
  a25=(a25+a64);
  a25=(a25/a36);
  a30=(a30*a25);
  a64=(a29*a30);
  a35=(a35-a64);
  a40=(a40*a25);
  a35=(a35-a40);
  a40=(a67+a67);
  a40=(a42*a40);
  a64=(a67/a15);
  a41=(a41*a25);
  a64=(a64-a41);
  a64=(a64/a15);
  a49=(a49*a25);
  a64=(a64-a49);
  a38=(a38*a64);
  a64=(a43*a20);
  a49=(a13*a07);
  a41=(a11*a18);
  a21=(a08*a63);
  a41=(a41-a21);
  a49=(a49+a41);
  a41=(a00*a27);
  a49=(a49+a41);
  a41=(a09*a49);
  a64=(a64-a41);
  a41=(a16*a54);
  a21=(a29*a67);
  a41=(a41+a21);
  a64=(a64+a41);
  a64=(a64/a15);
  a44=(a44*a25);
  a64=(a64-a44);
  a64=(a64/a15);
  a52=(a52*a25);
  a64=(a64-a52);
  a01=(a01*a64);
  a38=(a38+a01);
  a01=(a29*a20);
  a64=(a09*a54);
  a01=(a01+a64);
  a64=(a43*a67);
  a52=(a16*a49);
  a64=(a64-a52);
  a01=(a01-a64);
  a01=(a01/a15);
  a45=(a45*a25);
  a01=(a01-a45);
  a01=(a01/a15);
  a53=(a53*a25);
  a01=(a01-a53);
  a46=(a46*a01);
  a38=(a38+a46);
  a38=(a38/a36);
  a36=(a25+a25);
  a50=(a50*a36);
  a38=(a38-a50);
  a34=(a34*a38);
  a40=(a40+a34);
  a35=(a35-a40);
  a40=(a47*a49);
  a55=(a55*a25);
  a25=(a43*a55);
  a40=(a40+a25);
  a35=(a35+a40);
  a40=(a00*a35);
  a25=(a17*a20);
  a34=(a09*a30);
  a25=(a25-a34);
  a34=(a47*a67);
  a50=(a16*a55);
  a34=(a34-a50);
  a25=(a25-a34);
  a34=(a13*a25);
  a40=(a40+a34);
  a67=(a17*a67);
  a16=(a16*a30);
  a67=(a67-a16);
  a16=(a47*a20);
  a09=(a09*a55);
  a16=(a16-a09);
  a67=(a67+a16);
  a16=(a11*a67);
  a40=(a40+a16);
  a47=(a47*a54);
  a29=(a29*a55);
  a47=(a47-a29);
  a17=(a17*a49);
  a43=(a43*a30);
  a17=(a17+a43);
  a20=(a20+a20);
  a42=(a42*a20);
  a31=(a31*a38);
  a42=(a42+a31);
  a17=(a17+a42);
  a47=(a47-a17);
  a17=(a08*a47);
  a40=(a40+a17);
  a17=(a40/a03);
  a57=(a57*a14);
  a17=(a17-a57);
  a18=(a18/a03);
  a39=(a39*a14);
  a18=(a18-a39);
  a18=(a59*a18);
  a39=(a13*a67);
  a57=(a08*a35);
  a42=(a11*a25);
  a57=(a57+a42);
  a39=(a39-a57);
  a57=(a00*a47);
  a39=(a39+a57);
  a24=(a24*a39);
  a18=(a18+a24);
  a24=(a11*a35);
  a57=(a08*a25);
  a24=(a24-a57);
  a57=(a00*a67);
  a24=(a24-a57);
  a57=(a13*a47);
  a24=(a24+a57);
  a26=(a26*a24);
  a63=(a63/a03);
  a62=(a62*a14);
  a63=(a63+a62);
  a63=(a61*a63);
  a26=(a26-a63);
  a18=(a18+a26);
  a00=(a00*a25);
  a13=(a13*a35);
  a00=(a00-a13);
  a08=(a08*a67);
  a00=(a00-a08);
  a11=(a11*a47);
  a00=(a00+a11);
  a22=(a22*a00);
  a27=(a27/a03);
  a51=(a51*a14);
  a27=(a27+a51);
  a27=(a32*a27);
  a22=(a22-a27);
  a18=(a18+a22);
  a19=(a19*a40);
  a07=(a07/a03);
  a56=(a56*a14);
  a07=(a07+a56);
  a33=(a33*a07);
  a19=(a19-a33);
  a18=(a18+a19);
  a18=(a18/a37);
  a37=(a14+a14);
  a60=(a60*a37);
  a18=(a18-a60);
  a02=(a02*a18);
  a17=(a17-a02);
  if (res[0]!=0) res[0][3]=a17;
  if (res[0]!=0) res[0][4]=a48;
  a65=(a65/a03);
  a32=(a32/a03);
  a32=(a32/a03);
  a10=(a32*a10);
  a65=(a65-a10);
  a04=(a04+a04);
  a28=(a04*a28);
  a28=(a58+a28);
  a65=(a65-a28);
  if (res[0]!=0) res[0][5]=a65;
  a68=(a68/a03);
  a65=(a32*a12);
  a68=(a68-a65);
  a65=(a04*a23);
  a68=(a68-a65);
  if (res[0]!=0) res[0][6]=a68;
  a00=(a00/a03);
  a32=(a32*a14);
  a00=(a00-a32);
  a04=(a04*a18);
  a00=(a00-a04);
  if (res[0]!=0) res[0][7]=a00;
  if (res[0]!=0) res[0][8]=a69;
  if (res[0]!=0) res[0][9]=a68;
  a66=(a66/a03);
  a61=(a61/a03);
  a61=(a61/a03);
  a12=(a61*a12);
  a66=(a66-a12);
  a05=(a05+a05);
  a23=(a05*a23);
  a23=(a58+a23);
  a66=(a66-a23);
  if (res[0]!=0) res[0][10]=a66;
  a24=(a24/a03);
  a61=(a61*a14);
  a24=(a24-a61);
  a05=(a05*a18);
  a24=(a24-a05);
  if (res[0]!=0) res[0][11]=a24;
  if (res[0]!=0) res[0][12]=a17;
  if (res[0]!=0) res[0][13]=a00;
  if (res[0]!=0) res[0][14]=a24;
  a39=(a39/a03);
  a59=(a59/a03);
  a59=(a59/a03);
  a59=(a59*a14);
  a39=(a39-a59);
  a06=(a06+a06);
  a06=(a06*a18);
  a58=(a58+a06);
  a39=(a39-a58);
  if (res[0]!=0) res[0][15]=a39;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_ode_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_ode_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_ode_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_ode_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s1;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_ode_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_ode_cost_y_e_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
